# Generated by Django 4.0.4 on 2022-05-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=1000)),
                ('category', models.CharField(choices=[('SU', 'Succulents'), ('CA', 'Carnivorous'), ('BO', 'Bonsai'), ('FO', 'Foliage'), ('FL', 'Flowering')], max_length=2)),
                ('watering_frequency', models.CharField(max_length=50)),
                ('soil', models.CharField(max_length=50)),
                ('light_tolerance', models.CharField(max_length=50)),
            ],
        ),
    ]
